CASE_STUDIES = [
    {'title': 'Manus AI — 10M+ ephemeral databases for AI agents', 'url': 'https://www.pingcap.com/case-study/manus-agentic-ai-database-tidb/', 'summary': 'Manus AI runs 10 million ephemeral TiDB databases for AI agent swarms. Each agent creates isolated database contexts in milliseconds for the Decide-Validate-Remember episodic memory loop, writing decisions and outcomes back as vector embeddings so agents learn over time.'},
    {'title': 'Square (Block) — real-time financial analytics', 'url': 'https://www.pingcap.com/customers/', 'summary': 'Square uses TiDB for real-time financial transaction analytics across their payment processing platform, combining OLTP payment writes with analytical queries on the same live data without ETL delays.'},
    {'title': 'ZaloPay — payment processing at scale', 'url': 'https://www.pingcap.com/customers/', 'summary': 'ZaloPay migrated from sharded MySQL to TiDB Cloud to handle millions of payment transactions with HTAP analytics, eliminating complex sharding logic while maintaining ACID compliance for financial data.'},
    {'title': 'Bolt — ride-hailing real-time data', 'url': 'https://www.pingcap.com/case-study/bolt-modernizing-mysql-tidb-scale-thousands-microservices-aws/', 'summary': 'Bolt uses TiDB for real-time ride matching and pricing data, handling massive concurrent writes from drivers and riders with sub-second analytical queries for dynamic pricing and supply-demand optimization.'},
    {'title': 'Dailymotion — video platform analytics', 'url': 'https://www.pingcap.com/customers/', 'summary': 'Dailymotion consolidated their video analytics pipeline onto TiDB, replacing a fragmented stack of MySQL and analytics databases with unified HTAP for real-time content performance metrics and recommendation engine data.'},
    {'title': 'Automizely — e-commerce AI automation', 'url': 'https://www.pingcap.com/customers/', 'summary': 'Automizely uses TiDB to power their e-commerce automation SaaS platform, handling multi-tenant product catalog data, order analytics, and AI-driven marketing automation workflows with serverless scaling.'},
    {'title': 'PalFish — EdTech real-time matching', 'url': 'https://www.pingcap.com/customers/', 'summary': 'PalFish uses TiDB for real-time student-teacher matching in their online education platform, supporting concurrent session bookings and live class data with consistent low-latency reads and writes across time zones.'},
    {'title': 'BookMyShow — ticketing at massive scale', 'url': 'https://www.pingcap.com/case-study/tidb-in-bookmyshow/', 'summary': 'BookMyShow handles flash-sale ticket drops on TiDB with millions of concurrent seat selection requests, using distributed transactions to prevent overselling while running real-time sales analytics.'},
]
